### ISSUE TITLE
Separators in Firefox

### ISSUE THREAD

**Issue by ghost** [elibroftw/matte-black-theme#10]
Hello! how are you?
I have a problem with the separators because they don't appear in the Bookmarks Toolbar. Only a blank space appears.
This happens in the latest version of Firefox (84.0.2).

Thank you.

![Image](https://user-images.githubusercontent.com/77557959/104828685-d4720b00-584a-11eb-9dae-4acc3d07ebe3.png)

**Comment by elibroftw** [comment]
My bookmarks toolbar isn't working right now, but can you go to [about:debugging#/runtime/this-firefox](about:debugging#/runtime/this-firefox) and then install the attached file and let me know what you think or if it works at all.
[Matte Black (Red) Firefox.zip](https://github.com/elibroftw/matte-black-theme/files/5825409/Matte.Black.Red.Firefox.zip)

**Comment by ghost** [comment]
Yes! It works well. I generally use "matte black theme (blue)".

Thanks.

**Comment by elibroftw** [comment]
Okay I'll push an update in a couple hours.
