### ISSUE TITLE
Make download complete icon the same color as the accent 

### ISSUE THREAD

**Issue by ghost** [elibroftw/matte-black-theme#11]
title, need more info? just ask me.

**Comment by elibroftw** [comment]
Do you know a theme that does this? Otherwise its not possible, sorry. https://media.prod.mdn.mozit.cloud/attachments/2019/08/16/16855/e65c684251c682a17c783b2a18d60083/Themes_components_annotations.png.

**Comment by ghost** [comment]
https://addons.mozilla.org/nb-NO/firefox/addon/nicothin-dark-theme/?utm_content=addons-manager-reviews-link&utm_medium=firefox-browser&utm_source=firefox-browser

This one has yellow

**Comment by elibroftw** [comment]
Oh yeah my themes should already be doing this. May I ask which theme does not do this as I have many.

**Comment by ghost** [comment]
Matte Green started working just now!

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/57069715/107112778-7be6ca00-685a-11eb-9d36-b7f9fa449810.png)
and with favourites
![image](https://user-images.githubusercontent.com/57069715/107112793-96b93e80-685a-11eb-8d72-5fea27c26c6f.png)

**Comment by elibroftw** [comment]
Yeah there was a typo.
