### ISSUE TITLE
Instructions to build and use locally

### ISSUE THREAD

**Issue by NicolasCARPi** [elibroftw/matte-black-theme#14]
Hello,

I'm trying to modify it, then build and install from the local package, but firefox tells me it's corrupted. Could you please provide clear instructions on how to achieve that?

What I do:

* run the build.py script
* go to about:addons / themes and install from local file, selecting the .zip from the Builds folder

Please note that I have no knowledge about making themes ;)

Thanks :)

**Comment by elibroftw** [comment]
Go to debug add-ons and then you can install the zip. If you want a local installation you need to use amo to sign and self distribute.

**Comment by NicolasCARPi** [comment]
Thank you, I have added the instructions in the README: https://github.com/elibroftw/matte-black-theme/pull/16
