### ISSUE TITLE
Please take into account Menu bar users

### ISSUE THREAD

**Issue by com2** [elibroftw/matte-black-theme#18]
I am using the Matte Black (Orange) version because I hoped that it would not have the issue I will try to explain here. Some old fashioned users like to have the menu bar up there. With that active in your (and many other) Firefox theme I cannot read the first level of menu labels because there is not enough contrast with the background color of the theme. Not sure if the theme allows to adjust the Menu bar background color and/or font color to improve this? Below a screenshot with the mouse arrow pointing at the almost invisible menu bar. 
![image](https://user-images.githubusercontent.com/1062758/126373392-79976be9-66b1-46d5-9b41-662cdf8c291d.png)

The next screenshot shows the menu when I click one of the options. Obviously this is a work around not a fix. 
![image](https://user-images.githubusercontent.com/1062758/126373795-cd150e31-e3c8-4f41-8506-89f1df22e23f.png)

To encourage you; when you fix this,  you will for the moment be the only one with a dark theme that supports the Menu bar

**Comment by elibroftw** [comment]
It think this is a Linux issue. You should file a bug report with Mozilla Firefox.
This is how it looks like on Windows Firefox version 90.0.1 (64-bit).
![image](https://user-images.githubusercontent.com/21298211/126374202-091140d8-e570-4b61-8d12-24ef7623cb81.png)
![image](https://user-images.githubusercontent.com/21298211/126374338-41712f75-ad79-49b7-988b-4ae1bb74b6c1.png)

**Comment by com2** [comment]
I will wait for future versions to fix it then, because the bug was already filed.
