### ISSUE TITLE
Please make active tab more distinguished.

### ISSUE THREAD

**Issue by kruug** [elibroftw/matte-black-theme#2]
I don't believe there is enough of a difference between the active tab and inactive tabs.  When you have more than 5 tabs open, this makes it a bit difficult to discern where your current tab is.

**Comment by elibroftw** [comment]
is this for chrome or firefox?

**Comment by kruug** [comment]
Firefox.

**Comment by elibroftw** [comment]
Although I do think there's a noticeable difference, I will make it more noticeable soon.

**Comment by elibroftw** [comment]
I changed the background colour to be pitch black but that's the farthest I will personally change the contrast. It's only hard to distinguish by tab colour if the screen is not normal to my eyes. If its slanted up, I do agree it is hard to distinguish by tab colour but this is why I have the text on the current tab white and the text on other tabs grey.
