### ISSUE TITLE
Consider removing the white border on Matte Black

### ISSUE THREAD

**Issue by aydwi** [elibroftw/matte-black-theme#20]
Theme in question: https://addons.mozilla.org/en-US/firefox/addon/matte-black-v1/

The theme used to look like how the default dark theme looks on Firefox - no bright border around the tab; just a gray-ish current tab next to black/dark inactive tabs.
![image](https://user-images.githubusercontent.com/29029116/136063438-d5d68f91-e09c-482e-9240-1bd2ceef57a8.png)

How it looks now on Windows/Firefox 93.0:
![image](https://user-images.githubusercontent.com/29029116/136062255-1d13a7a9-1522-4c5e-beff-d35121520e07.png)

The new border looks very distracting. I can understand its usage as an accent color in other variants, but "Matte Black" should not have any white border.

**Comment by elibroftw** [comment]
My bad, I had uploaded a new version yesterday and didn't realize it was missing some changes. It should be good now.

**Comment by aydwi** [comment]
@elibroftw Can confirm, the fix is live. Thanks for your work on these themes and the quick fix.
