### ISSUE TITLE
Background tab color for Matte Black (Grey) Firefox is too bright

### ISSUE THREAD

**Issue by friedkeenan** [elibroftw/matte-black-theme#21]
I was using my browser late last night with a headache, and then suddenly the outline of the currently selected tab became bright white:
![image](https://user-images.githubusercontent.com/20881398/136089996-ad5b7a1c-f51f-44a6-9d1b-d7c5c76ca860.png)

It took me a while to track it down to the theme updating, and then to commit ac0572fec74e00c155a0554692a9ceca08df6bd6.

This is what it looked like before:
![image](https://user-images.githubusercontent.com/20881398/136090188-946c8905-a066-494a-8622-3d5272d8b84a.png)

It would be nice to get the previous coloring back in the theme as I can only load a theme with that commit reverted temporarily

**Comment by elibroftw** [comment]
I just fixed this today morning, just update the theme. And you can't really track it down since the version you are using is matte black grey and for some reason I didn't update the source code to match the version.
