### ISSUE TITLE
Matte Black Red doesn't function as a dark theme

### ISSUE THREAD

**Issue by Lxran** [elibroftw/matte-black-theme#23]
Hello! I have noticed that since updating to Firefox v100 (I think; I didn't notice in the older versions) many of the styling of pages that depend on the browser's dark theme selection show up as if Matte Black Red was a light theme. For example, PDF.js pages are in light theme mode, even though it was in dark theme mode before.

Is this intentional? If not, is there anything I can add to this report to make it easier for you?

Many thanks for making this theme as well, it's my favourite so far :)

**Comment by elibroftw** [comment]
It's not intentional as a theme does not style pages, only the browser's own UI.

Can you share screenshots? Can you see if any other 3rd party dark theme behaves the same. If not let me know which one.

**Comment by Lxran** [comment]
Well, I went to the Firefox Addons and installed a bunch of "dark" themes, but none of them seem to trigger the "dark" styling in the browser. 

The themes I tried: 
- https://addons.mozilla.org/en-GB/firefox/addon/dark-theme69/
- https://addons.mozilla.org/en-GB/firefox/addon/nicothin-dark-theme/
- https://addons.mozilla.org/en-GB/firefox/addon/nicothin-space/
- https://addons.mozilla.org/en-GB/firefox/addon/nicothin-dark-magic/

I also found the setting for the preferred styling in the browser, this one: https://files.catbox.moe/cnehv9.png
If it is left as "Firefox Theme", it will not be dark, instead it will be light: https://files.catbox.moe/fsezlu.png

I did not have to turn this on before, but this theme (and the others, for that matter) work as expected when "Dark" is selected.

**Comment by elibroftw** [comment]
So has your issue been solved then? It's a Firefox issue not a theme issue so I'm closing.
