### ISSUE TITLE
White tab outline on Firefox v122

### ISSUE THREAD

**Issue by epic0421** [elibroftw/matte-black-theme#26]
When using the Matte Black theme, there is a white tab outline that has appeared since Firefox v122 has released which was not present before.

**Comment by epic0421** [comment]
There are likely other changes too that I am not aware of yet, but this change is the one that I noticed right away.

**Comment by elibroftw** [comment]
Will take a look at it.

**Comment by elibroftw** [comment]
Let me know if the issue is fixed

**Comment by epic0421** [comment]
That does seem to fix it. When I was loading it as a temporary add-on, I noticed this:
![image](https://github.com/elibroftw/matte-black-theme/assets/85042398/87ac0872-6425-4633-9fff-73bcde264cde)
Not sure if you want to remove that property. This property probably exists with all versions of your theme.

**Comment by elibroftw** [comment]
I was going to remove that but it wasn't giving warnings in 2022. Guess I will remove it now.
