### ISSUE TITLE
[Firefox] Search bar is no longer using theme colors

### ISSUE THREAD

**Issue by ashucg** [elibroftw/matte-black-theme#3]
I am using **Firefox Nightly 68.0a1 (2019-04-11) (64-bit)** and as you can see in the following screenshot, search bar is no longer using theme color scheme:

![image](https://user-images.githubusercontent.com/11291284/56045796-6e7d5900-5d31-11e9-8431-941ea1837feb.png)

It is working fine on **Firefox Developer Edition 67.0b9 (64-bit)**:

![image](https://user-images.githubusercontent.com/11291284/56045935-ba300280-5d31-11e9-9067-7b69e0d7503c.png)

But with an issue that arrows are hard to see.

It would be great if you could fix this and change contrast as well.

**Comment by elibroftw** [comment]
Do you mean the find in page search bar? This issue seems like a firefox issue, not a theme issue.
The contrast becomes apparent once there's a character in the find in page bar on the latest version of Firefox. 
![image](https://user-images.githubusercontent.com/21298211/56086992-4294cd00-5e30-11e9-93f7-f78556cd361c.png)

**Comment by ashucg** [comment]
> Do you mean the find in page search bar?

Yes, I'm talking about that.

> This issue seems like a firefox issue, not a theme issue.

Okay, but this doesn't happen if I activate default dark theme. Maybe they have changed something in Firefox 68? I would create a bug report about it tomorrow if you still believe it's a Firefox issue.

> The contrast becomes apparent once there's a character in the find in page bar

Yes, it does, but looks a bit weird initially, without any value. But it's certainly not an issue, more like my personal perspective and can be ignored.

**Comment by elibroftw** [comment]
I'll try to see if this issue exists on other themes.

Elijah Lopez

**Comment by ashucg** [comment]
It is a [Firefox bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1549014)
